"""Initial migration

Revision ID: 0f374ca406ca
Revises: 
Create Date: 2024-04-08 00:54:24.885991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f374ca406ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oprf_key')
    op.drop_column('users', 'salt')
    op.drop_column('users', 'server_public_key')
    op.drop_column('users', 'encrypted_record')
    op.drop_column('users', 'encrypted_envelope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_envelope', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('encrypted_record', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('server_public_key', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('salt', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('oprf_key', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
