"""Add nonce, tag, and encryption_key columns

Revision ID: 17384434efa8
Revises: 7aaa2279567b
Create Date: 2024-05-14 22:23:20.078562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17384434efa8'
down_revision: Union[str, None] = '7aaa2279567b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
