"""describe your changes here

Revision ID: 6db7a1456d33
Revises: 7b36ece1a1d1
Create Date: 2024-05-14 22:29:18.981378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db7a1456d33'
down_revision: Union[str, None] = '7b36ece1a1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 's3_key')
    # ### end Alembic commands ###
