"""Add nonce, tag, and encryption_key columns

Revision ID: 7aaa2279567b
Revises: 8edf75486c17
Create Date: 2024-05-14 22:12:01.717438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aaa2279567b'
down_revision: Union[str, None] = '8edf75486c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('encryption_key_s', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'encryption_key_s')
    # ### end Alembic commands ###
