"""Add content_type to FileMetadata

Revision ID: 7b36ece1a1d1
Revises: 0f374ca406ca
Create Date: 2024-05-11 17:30:39.510752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36ece1a1d1'
down_revision: Union[str, None] = '0f374ca406ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('file_content', sa.String(), nullable=True))
    op.add_column('file_metadata', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'content_type')
    op.drop_column('file_metadata', 'file_content')
    # ### end Alembic commands ###
